services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secure-social-backend
    ports:
      - "8000:8000"
    volumes:
      - ./firebase.json:/app/firebase.json
      # - ./backend/data:/app/data
      - ./backend/src:/app/src
      - ./backend/run_web.py:/app/run_web.py
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secure-social-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
    restart: unless-stopped
